-- MySQL Script generated by MySQL Workbench
-- Fri Apr 22 00:38:21 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`MImg`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MImg` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MImg` (
  `id_img` INT NOT NULL AUTO_INCREMENT,
  `ruta` VARCHAR(150) NULL,
  PRIMARY KEY (`id_img`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CAnio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CAnio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CAnio` (
  `id_anio` INT NOT NULL AUTO_INCREMENT,
  `anio` INT NULL,
  PRIMARY KEY (`id_anio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CMes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CMes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CMes` (
  `id_mes` INT NOT NULL AUTO_INCREMENT,
  `mes` INT NULL,
  PRIMARY KEY (`id_mes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CDia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CDia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CDia` (
  `id_dia` INT NOT NULL AUTO_INCREMENT,
  `dia` INT NULL,
  PRIMARY KEY (`id_dia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CHora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CHora` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CHora` (
  `id_hora` INT NOT NULL AUTO_INCREMENT,
  `hora` INT NULL,
  PRIMARY KEY (`id_hora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MFecha`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MFecha` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MFecha` (
  `id_fecha` INT NOT NULL AUTO_INCREMENT,
  `id_anio` INT NOT NULL,
  `CMes_id_mes` INT NOT NULL,
  `CDia_id_dia` INT NOT NULL,
  `CHora_id_hora` INT NOT NULL,
  PRIMARY KEY (`id_fecha`, `id_anio`, `CMes_id_mes`, `CDia_id_dia`, `CHora_id_hora`),
  INDEX `fk_MFecha_CAnio_idx` (`id_anio` ASC) VISIBLE,
  INDEX `fk_MFecha_CMes1_idx` (`CMes_id_mes` ASC) VISIBLE,
  INDEX `fk_MFecha_CDia1_idx` (`CDia_id_dia` ASC) VISIBLE,
  INDEX `fk_MFecha_CHora1_idx` (`CHora_id_hora` ASC) VISIBLE,
  CONSTRAINT `fk_MFecha_CAnio`
    FOREIGN KEY (`id_anio`)
    REFERENCES `mydb`.`CAnio` (`id_anio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MFecha_CMes1`
    FOREIGN KEY (`CMes_id_mes`)
    REFERENCES `mydb`.`CMes` (`id_mes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MFecha_CDia1`
    FOREIGN KEY (`CDia_id_dia`)
    REFERENCES `mydb`.`CDia` (`id_dia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MFecha_CHora1`
    FOREIGN KEY (`CHora_id_hora`)
    REFERENCES `mydb`.`CHora` (`id_hora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CGrupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CGrupo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CGrupo` (
  `id_grupo` INT NOT NULL AUTO_INCREMENT,
  `grupo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_grupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CSexo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CSexo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CSexo` (
  `id_sexo` INT NOT NULL AUTO_INCREMENT,
  `sexo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_sexo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CSemestre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CSemestre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CSemestre` (
  `id_semestre` INT NOT NULL AUTO_INCREMENT,
  `semestre` INT NULL,
  PRIMARY KEY (`id_semestre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CRol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CRol` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CRol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CPrivilegio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CPrivilegio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CPrivilegio` (
  `id_privilegio` INT NOT NULL AUTO_INCREMENT,
  `privilegio` VARCHAR(45) NULL,
  PRIMARY KEY (`id_privilegio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DPersona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DPersona` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DPersona` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `appat` VARCHAR(100) NULL,
  `apmat` VARCHAR(100) NULL,
  `usuario` VARCHAR(100) NULL,
  `contraseña` VARCHAR(100) NULL,
  `id_img` INT NOT NULL,
  `id_fecha` INT NOT NULL,
  `id_grupo` INT NOT NULL,
  `id_sexo` INT NOT NULL,
  `id_semestre` INT NOT NULL,
  `id_rol` INT NOT NULL,
  `id_privilegio` INT NOT NULL,
  PRIMARY KEY (`id_persona`, `id_img`, `id_fecha`, `id_grupo`, `id_sexo`, `id_semestre`, `id_rol`, `id_privilegio`),
  INDEX `fk_DPersona_MImg1_idx` (`id_img` ASC) VISIBLE,
  INDEX `fk_DPersona_MFecha1_idx` (`id_fecha` ASC) VISIBLE,
  INDEX `fk_DPersona_CGrupo1_idx` (`id_grupo` ASC) VISIBLE,
  INDEX `fk_DPersona_CSexo1_idx` (`id_sexo` ASC) VISIBLE,
  INDEX `fk_DPersona_CSemestre1_idx` (`id_semestre` ASC) VISIBLE,
  INDEX `fk_DPersona_CRol1_idx` (`id_rol` ASC) VISIBLE,
  INDEX `fk_DPersona_CPrivilegio1_idx` (`id_privilegio` ASC) VISIBLE,
  CONSTRAINT `fk_DPersona_MImg1`
    FOREIGN KEY (`id_img`)
    REFERENCES `mydb`.`MImg` (`id_img`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DPersona_MFecha1`
    FOREIGN KEY (`id_fecha`)
    REFERENCES `mydb`.`MFecha` (`id_fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DPersona_CGrupo1`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `mydb`.`CGrupo` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DPersona_CSexo1`
    FOREIGN KEY (`id_sexo`)
    REFERENCES `mydb`.`CSexo` (`id_sexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DPersona_CSemestre1`
    FOREIGN KEY (`id_semestre`)
    REFERENCES `mydb`.`CSemestre` (`id_semestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DPersona_CRol1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `mydb`.`CRol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DPersona_CPrivilegio1`
    FOREIGN KEY (`id_privilegio`)
    REFERENCES `mydb`.`CPrivilegio` (`id_privilegio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '						';


-- -----------------------------------------------------
-- Table `mydb`.`MPersona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MPersona` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MPersona` (
  `boleta` INT NOT NULL AUTO_INCREMENT,
  `id_person` INT NOT NULL,
  PRIMARY KEY (`boleta`, `id_person`),
  INDEX `fk_MPersona_DPersona1_idx` (`id_person` ASC) VISIBLE,
  CONSTRAINT `fk_MPersona_DPersona1`
    FOREIGN KEY (`id_person`)
    REFERENCES `mydb`.`DPersona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CAsignatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CAsignatura` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CAsignatura` (
  `id_aignatura` INT NOT NULL AUTO_INCREMENT,
  `asignatura` VARCHAR(45) NULL,
  PRIMARY KEY (`id_aignatura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CMarca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CMarca` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CMarca` (
  `id_marca` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NULL,
  PRIMARY KEY (`id_marca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MAccesorios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MAccesorios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MAccesorios` (
  `id_accesorios` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(500) NULL,
  `id_marca` INT NOT NULL,
  PRIMARY KEY (`id_accesorios`, `id_marca`),
  INDEX `fk_MAccesorios_CMarca1_idx` (`id_marca` ASC) VISIBLE,
  CONSTRAINT `fk_MAccesorios_CMarca1`
    FOREIGN KEY (`id_marca`)
    REFERENCES `mydb`.`CMarca` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLab`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CLab` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CLab` (
  `id_Lab` INT NOT NULL AUTO_INCREMENT,
  `laboratorio` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Lab`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MConfirguracion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MConfirguracion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MConfirguracion` (
  `id_config` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(500) NULL,
  `id_marca` INT NOT NULL,
  PRIMARY KEY (`id_config`, `id_marca`),
  INDEX `fk_MConfirguracion_CMarca1_idx` (`id_marca` ASC) VISIBLE,
  CONSTRAINT `fk_MConfirguracion_CMarca1`
    FOREIGN KEY (`id_marca`)
    REFERENCES `mydb`.`CMarca` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MCPU`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MCPU` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MCPU` (
  `serial_cpu` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(500) NULL,
  `id_marca` INT NOT NULL,
  PRIMARY KEY (`serial_cpu`, `id_marca`),
  INDEX `fk_MCPU_CMarca1_idx` (`id_marca` ASC) VISIBLE,
  CONSTRAINT `fk_MCPU_CMarca1`
    FOREIGN KEY (`id_marca`)
    REFERENCES `mydb`.`CMarca` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MMonitor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MMonitor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MMonitor` (
  `serial_monitor` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(500) NULL,
  `id_marca` INT NOT NULL,
  PRIMARY KEY (`serial_monitor`, `id_marca`),
  INDEX `fk_MMonitor_CMarca1_idx` (`id_marca` ASC) VISIBLE,
  CONSTRAINT `fk_MMonitor_CMarca1`
    FOREIGN KEY (`id_marca`)
    REFERENCES `mydb`.`CMarca` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MEquipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MEquipo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MEquipo` (
  `id_equipo` INT NOT NULL AUTO_INCREMENT,
  `equipo_etiqueta` INT NULL,
  `id_accesorios` INT NOT NULL,
  `id_Lab` INT NOT NULL,
  `id_config` INT NOT NULL,
  `MCPU_serial_cpu` VARCHAR(100) NOT NULL,
  `MMonitor_serial_monitor` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_equipo`, `id_accesorios`, `id_Lab`, `id_config`, `MCPU_serial_cpu`, `MMonitor_serial_monitor`),
  INDEX `fk_MEquipo_MAccesorios1_idx` (`id_accesorios` ASC) VISIBLE,
  INDEX `fk_MEquipo_CLab1_idx` (`id_Lab` ASC) VISIBLE,
  INDEX `fk_MEquipo_MConfirguracion1_idx` (`id_config` ASC) VISIBLE,
  UNIQUE INDEX `id_config_UNIQUE` (`id_config` ASC) VISIBLE,
  INDEX `fk_MEquipo_MCPU1_idx` (`MCPU_serial_cpu` ASC) VISIBLE,
  INDEX `fk_MEquipo_MMonitor1_idx` (`MMonitor_serial_monitor` ASC) VISIBLE,
  CONSTRAINT `fk_MEquipo_MAccesorios1`
    FOREIGN KEY (`id_accesorios`)
    REFERENCES `mydb`.`MAccesorios` (`id_accesorios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MEquipo_CLab1`
    FOREIGN KEY (`id_Lab`)
    REFERENCES `mydb`.`CLab` (`id_Lab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MEquipo_MConfirguracion1`
    FOREIGN KEY (`id_config`)
    REFERENCES `mydb`.`MConfirguracion` (`id_config`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MEquipo_MCPU1`
    FOREIGN KEY (`MCPU_serial_cpu`)
    REFERENCES `mydb`.`MCPU` (`serial_cpu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MEquipo_MMonitor1`
    FOREIGN KEY (`MMonitor_serial_monitor`)
    REFERENCES `mydb`.`MMonitor` (`serial_monitor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MRegistro_de_Equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MRegistro_de_Equipo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MRegistro_de_Equipo` (
  `id_registro` INT NOT NULL AUTO_INCREMENT,
  `boleta` INT NOT NULL,
  `id_aignatura` INT NOT NULL,
  `id_equipo` INT NOT NULL,
  PRIMARY KEY (`id_registro`, `boleta`, `id_aignatura`, `id_equipo`),
  INDEX `fk_MRegistro_de_Equipo_MPersona1_idx` (`boleta` ASC) VISIBLE,
  INDEX `fk_MRegistro_de_Equipo_CAsignatura1_idx` (`id_aignatura` ASC) VISIBLE,
  INDEX `fk_MRegistro_de_Equipo_MEquipo1_idx` (`id_equipo` ASC) VISIBLE,
  CONSTRAINT `fk_MRegistro_de_Equipo_MPersona1`
    FOREIGN KEY (`boleta`)
    REFERENCES `mydb`.`MPersona` (`boleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MRegistro_de_Equipo_CAsignatura1`
    FOREIGN KEY (`id_aignatura`)
    REFERENCES `mydb`.`CAsignatura` (`id_aignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MRegistro_de_Equipo_MEquipo1`
    FOREIGN KEY (`id_equipo`)
    REFERENCES `mydb`.`MEquipo` (`id_equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CPrioridad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CPrioridad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CPrioridad` (
  `id_prioridad` INT NOT NULL AUTO_INCREMENT,
  `prioridad` VARCHAR(45) NULL,
  PRIMARY KEY (`id_prioridad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MProblema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MProblema` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MProblema` (
  `id_problema` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(500) NULL,
  PRIMARY KEY (`id_problema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DReporte_de_Equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DReporte_de_Equipo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DReporte_de_Equipo` (
  `id_dreporte` INT NOT NULL AUTO_INCREMENT,
  `id_aignatura` INT NOT NULL,
  `id_fecha` INT NOT NULL,
  `id_equipo` INT NOT NULL,
  `id_prioridad` INT NOT NULL,
  `boleta` INT NOT NULL,
  `id_problema` INT NOT NULL,
  PRIMARY KEY (`id_dreporte`, `id_aignatura`, `id_fecha`, `id_equipo`, `id_prioridad`, `boleta`, `id_problema`),
  INDEX `fk_DReporte_de_Equipo_CAsignatura1_idx` (`id_aignatura` ASC) VISIBLE,
  INDEX `fk_DReporte_de_Equipo_MFecha1_idx` (`id_fecha` ASC) VISIBLE,
  INDEX `fk_DReporte_de_Equipo_MEquipo1_idx` (`id_equipo` ASC) VISIBLE,
  INDEX `fk_DReporte_de_Equipo_CPrioridad1_idx` (`id_prioridad` ASC) VISIBLE,
  INDEX `fk_DReporte_de_Equipo_MPersona1_idx` (`boleta` ASC) VISIBLE,
  INDEX `fk_DReporte_de_Equipo_MProblema1_idx` (`id_problema` ASC) VISIBLE,
  CONSTRAINT `fk_DReporte_de_Equipo_CAsignatura1`
    FOREIGN KEY (`id_aignatura`)
    REFERENCES `mydb`.`CAsignatura` (`id_aignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DReporte_de_Equipo_MFecha1`
    FOREIGN KEY (`id_fecha`)
    REFERENCES `mydb`.`MFecha` (`id_fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DReporte_de_Equipo_MEquipo1`
    FOREIGN KEY (`id_equipo`)
    REFERENCES `mydb`.`MEquipo` (`id_equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DReporte_de_Equipo_CPrioridad1`
    FOREIGN KEY (`id_prioridad`)
    REFERENCES `mydb`.`CPrioridad` (`id_prioridad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DReporte_de_Equipo_MPersona1`
    FOREIGN KEY (`boleta`)
    REFERENCES `mydb`.`MPersona` (`boleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DReporte_de_Equipo_MProblema1`
    FOREIGN KEY (`id_problema`)
    REFERENCES `mydb`.`MProblema` (`id_problema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MEstado_de_Reporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MEstado_de_Reporte` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MEstado_de_Reporte` (
  `id_estado_de_reporte` INT NOT NULL AUTO_INCREMENT,
  `estado_de_reporte` VARCHAR(45) NULL,
  PRIMARY KEY (`id_estado_de_reporte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MReporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MReporte` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MReporte` (
  `id_reporte` INT NOT NULL AUTO_INCREMENT,
  `id_dreporte` INT NOT NULL,
  `id_estado_de_reporte` INT NOT NULL,
  PRIMARY KEY (`id_reporte`, `id_dreporte`, `id_estado_de_reporte`),
  INDEX `fk_MReporte_DReporte_de_Equipo1_idx` (`id_dreporte` ASC) VISIBLE,
  INDEX `fk_MReporte_MEstado_de_Reporte1_idx` (`id_estado_de_reporte` ASC) VISIBLE,
  CONSTRAINT `fk_MReporte_DReporte_de_Equipo1`
    FOREIGN KEY (`id_dreporte`)
    REFERENCES `mydb`.`DReporte_de_Equipo` (`id_dreporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MReporte_MEstado_de_Reporte1`
    FOREIGN KEY (`id_estado_de_reporte`)
    REFERENCES `mydb`.`MEstado_de_Reporte` (`id_estado_de_reporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
